### ISSUE TITLE
Problem installing with Docker using Dockerfile.

### ISSUE THREAD

**Issue by NightZpy** [ricekab/sqlalchemy-seeder#6]
```
FROM python:3.6

RUN mkdir -p /usr/src/app
COPY . /usr/src/app
WORKDIR /usr/src/app

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install sqlalchemy-seeder

#Run Microservice

EXPOSE 8080
CMD ["python", "main.py"]
```

After build container, when I run:

```
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from sqlalchemyseeder import ResolvingSeeder
ModuleNotFoundError: No module named 'sqlalchemyseeder'
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from sqlalchemyseeder import ResolvingSeeder
ModuleNotFoundError: No module named 'sqlalchemyseeder'
```

What's is the problem, why doesn't found the module after install?

**Comment by RiceKab** [comment]
I don't have much experience with Docker but my first guess would be that the issue lies with the path not being correct.

To confirm this you could just install another package and try to import it in the same way, it should fail all the same.

Or you can just check the path directly and see if it is what you'd expect.

**Comment by NightZpy** [comment]
Hi @RiceKab thanks for your support.

All others packages works fine! And the install process is the same. After that, I extract your package from requirements.txt for check de problem but the problem still up!
